name: viz_landscape
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=3.2.0
  - bokeh=1.3.4
  - jupyterlab=1.1.4
  - matplotlib=3.1.1
  - pandas=0.25.1
  - python=3.7.3
  - plotly=4.1.1
  - seaborn=0.9.0
  - vega_datasets=0.7.0
